version: '3'
services:
  jupyterlab:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    working_dir: '/src'
    tty: true
    volumes:
      - ./src:/src
    ports: 
      - "18000:18000"
    command: jupyter-lab --ip 0.0.0.0 --port=18000 --allow-root --no-browser